language: python
python:
  - "3.3"
  - "3.4"
branches:
  only:
    - master
env:
  - DJANGO_VERSION=1.7.7
  - DJANGO_VERSION=1.8
install:
  - pip install -q django==$DJANGO_VERSION
  - pip install -r requirements.txt
  - pip install -r tests/requirements.txt
  - pip install coveralls
  - python setup.py -q install
script:
  - cd tests && coverage run manage.py test
after_success: 
  - coveralls --rcfile=../.coveragerc