language: python
python:
  - "3.3"
  - "3.4"
branches:
  only:
    - master
env:
  - DJANGO_VERSION=">=1.7,<1.8"
  - DJANGO_VERSION=">=1.8,<1.9"
install:
  - pip install django$DJANGO_VERSION
  - pip install -r requirements.txt
  - pip install -r tests/requirements.txt
  - pip install coveralls
  - python setup.py -q install
script:
  - cd tests && coverage run manage.py test
after_success: 
  - coveralls --rcfile=../.coveragerc