language: python
python:
  - "2.7"
  - "3.3"
branches:
  only:
    - master
env:
  - DJANGO_VERSION=1.6.7
matrix:
  include:
    - python: "3.3"
      env: DJANGO_VERSION=1.7
    - python: "3.4"
      env: DJANGO_VERSION=1.7
install:
  - pip install -q django==$DJANGO_VERSION
  - pip install -r requirements.txt
  - pip install -r tests/requirements.txt
  - pip install coveralls
  - python setup.py -q install
script:
  - cd tests && coverage run manage.py test
after_success: 
  - coveralls --rcfile=../.coveragerc