sudo: false
language: python
python:
  - "3.4"
  - "3.5"
branches:
  only:
    - master
env:
  - DJANGO_VERSION=">=1.8,<1.9"
  - DJANGO_VERSION=">=1.9,<1.10"
matrix:
  exclude:
    - python: "3.5"
      env: DJANGO_VERSION=">=1.8,<1.9"
install:
  - pip install -r requirements.txt
  - pip install -r tests/requirements.txt
  - pip install django$DJANGO_VERSION
  - pip install coveralls
  - python setup.py -q install
script:
  - cd tests && coverage run manage.py test
after_success: 
  - coveralls --rcfile=../.coveragerc