from __future__ import unicode_literals


# List of english bad words
BAD_WORDS_EN = [
    '2g1c', '2girls1cup', '4r5e', '5h1t', '5hit', '@$$', 'a55', 'a_s_s',
    'acrotomophilia', 'ahole', 'amcik', 'anal', 'andskota', 'anilingus',
    'anus', 'ar5e', 'arrse', 'arschloch', 'arse', 'arsehole', 'ash0le',
    'ash0les', 'asholes', 'ass', 'ass-fucker', 'asses', 'assface', 'assfucker',
    'assfukka', 'assh0le', 'assh0lez', 'asshole', 'assholes', 'assholz',
    'assmonkey', 'assmunch', 'assrammer', 'asswhole', 'asswipe', 'autoerotic',
    'ayir', 'azzhole', 'b!+ch', 'b!tch', 'b00b', 'b00bs', 'b17ch', 'b1tch',
    'babeland', 'babybatter', 'ballbag', 'ballgag', 'ballgravy', 'ballkicking',
    'balllicking', 'balls', 'ballsack', 'ballsucking', 'bangbros', 'bareback',
    'barelylegal', 'barenaked', 'bassterds', 'bastard', 'bastardo', 'bastards',
    'bastardz', 'basterds', 'basterdz', 'bastinado', 'bbw', 'bdsm', 'beastial',
    'beastiality', 'beavercleaver', 'beaverlips', 'bellend', 'bestial',
    'bestiality', 'bi+ch', 'bi7ch', 'biatch', 'bicurious', 'bigblack',
    'bigbreasts', 'bigknockers', 'bigtits', 'bimbos', 'birdlock', 'bitch',
    'bitcher', 'bitchers', 'bitches', 'bitchin', 'bitching', 'blackcock',
    'blondeaction', 'blondeonblondeaction', 'bloody', 'blowj', 'blowjob',
    'blowjobs', 'blowyourl', 'bluewaffle', 'blumpkin', 'boffing', 'boiolas',
    'bollock', 'bollocks', 'bollok', 'bondage', 'boner', 'boob', 'boobs',
    'booobs', 'boooobs', 'booooobs', 'booooooobs', 'bootycall', 'breasts',
    'brownshowers', 'brunetteaction', 'buceta', 'bugger', 'bukkake',
    'bulldyke', 'bulletvibe', 'bum', 'bunghole', 'bunnyfucker', 'busty',
    'butt', 'butt-pirate', 'buttcheeks', 'butthole', 'buttmuch', 'buttplug',
    'buttwipe', 'c0ck', 'c0cks', 'c0cksucker', 'c0k', 'cabron', 'cameltoe',
    'camgirl', 'camslut', 'camwhore', 'carpetmuncher', 'cawk', 'cawks',
    'cazzo', 'chink', 'chocolaterosebuds', 'chraa', 'chuj', 'cipa',
    'circlejerk', 'cl1t', 'clevelandsteamer', 'clit', 'clitoris', 'clits',
    'cloverclamps', 'clusterfuck', 'cnts', 'cntz', 'cnut', 'cock', 'cock-head',
    'cock-sucker', 'cockface', 'cockhead', 'cockmunch', 'cockmuncher',
    'cocks', 'cocksuck', 'cocksucked', 'cocksucker', 'cocksucking',
    'cocksucks', 'cocksuka', 'cocksukka', 'cok', 'cokmuncher', 'coksucka',
    'coon', 'coprolagnia', 'coprophilia', 'cornhole', 'cox', 'crap', 'cum',
    'cummer', 'cumming', 'cums', 'cumshot', 'cunilingus', 'cunillingus',
    'cunnilingus', 'cunt', 'cuntlick', 'cuntlicker', 'cuntlicking', 'cunts',
    'cuntz', 'cyalis', 'cyberfuc', 'cyberfuck', 'cyberfucked', 'cyberfucker',
    'cyberfuckers', 'cyberfucking', 'd1ck', 'd4mn', 'damn', 'darkie',
    'daterape', 'daygo', 'deepthroat', 'dego', 'dick', 'dickhead', 'dike',
    'dild0', 'dild0s', 'dildo', 'dildos', 'dilld0', 'dilld0s', 'dink', 'dinks',
    'dirsa', 'dirtypillows', 'dirtysanchez', 'dlck', 'dog-fucker',
    'doggiestyle', 'doggin', 'dogging', 'doggystyle', 'dogstyle', 'dolcett',
    'domination', 'dominatricks', 'dominatrics', 'dominatrix', 'dommes',
    'donkeypunch', 'donkeyribber', 'doosh', 'doubledong', 'doublepenetration',
    'dpaction', 'duche', 'dupa', 'dyke', 'dziwka', 'eatmyass', 'ecchi',
    'ejackulate', 'ejaculate', 'ejaculated', 'ejaculates', 'ejaculating',
    'ejaculatings', 'ejaculation', 'ejakulate', 'ekrem', 'ekto', 'enculer',
    'enema', 'erotic', 'erotism', 'escort', 'ethicalslut', 'eunuch', 'f4nny',
    'f_u_c_k', 'faen', 'fag', 'fag1t', 'faget', 'fagg1t', 'fagging', 'faggit',
    'faggitt', 'faggot', 'faggs', 'fagit', 'fagot', 'fagots', 'fags', 'fagz',
    'faig', 'faigs', 'fanculo', 'fanny', 'fannyflaps', 'fannyfucker', 'fanyy',
    'fart', 'fatass', 'fcuk', 'fcuker', 'fcuking', 'fecal', 'feces', 'feck',
    'fecker', 'feg', 'felch', 'felcher', 'felching', 'fellate', 'fellatio',
    'feltch', 'femalesquirting', 'femdom', 'ficken', 'figging', 'fingerfuck',
    'fingerfucked', 'fingerfucker', 'fingerfuckers', 'fingerfucking',
    'fingerfucks', 'fingering', 'fistfuck', 'fistfucked', 'fistfucker',
    'fistfuckers', 'fistfucking', 'fistfuckings', 'fistfucks', 'fisting',
    'fitt', 'flange', 'flikker', 'flippingthebird', 'fook', 'fooker',
    'footfetish', 'footjob', 'foreskin', 'fotze', 'frotting', 'fu(', 'fuck',
    'fucka', 'fuckbuttons', 'fucked', 'fucker', 'fuckers', 'fuckhead',
    'fuckheads', 'fuckin', 'fucking', 'fuckings', 'fuckingshitmotherfucker',
    'fuckme', 'fucks', 'fuckwhit', 'fuckwit', 'fudgepacker', 'fuk', 'fukah',
    'fuken', 'fuker', 'fukin', 'fukk', 'fukkah', 'fukken', 'fukker', 'fukkin',
    'fuks', 'fukwhit', 'fukwit', 'futanari', 'futkretzn', 'fux', 'fux0r',
    'g-spot', 'g00k', 'gangbang', 'gangbanged', 'gangbangs', 'gay', 'gayboy',
    'gaygirl', 'gaylord', 'gays', 'gaysex', 'gayz', 'genitals', 'giantcock',
    'girlon', 'girlontop', 'girlsgonewild', 'goatcx', 'goatse', 'god',
    'god-dam', 'god-damned', 'goddamn', 'goddamned', 'gokkun', 'goldenshower',
    'goodpoop', 'googirl', 'gook', 'goregasm', 'grope', 'groupsex', 'guiena',
    'guro', 'h00r', 'h0ar', 'h0r', 'h0re', 'h4x0r', 'handjob', 'hardcore',
    'hardcoresex', 'hell', 'hells', 'helvete', 'hentai', 'heshe', 'hoar',
    'hoare', 'hoer', 'homo', 'homoerotic', 'honkey', 'hooker', 'hoor', 'hoore',
    'hore', 'horniest', 'horny', 'hotchick', 'hotsex', 'howtokill',
    'howtomurder', 'huevon', 'hugefat', 'hui', 'humping', 'incest', 'injun',
    'intercourse', 'jack-off', 'jackoff', 'jailbait', 'jap', 'japs',
    'jerk-off', 'jerkoff', 'jigaboo', 'jiggaboo', 'jiggerboo', 'jisim', 'jism',
    'jiss', 'jiz', 'jizm', 'jizz', 'juggs', 'kanker', 'kawk', 'kike',
    'kinbaku', 'kinkster', 'kinky', 'klootzak', 'knob', 'knobbing', 'knobead',
    'knobed', 'knobend', 'knobhead', 'knobjocky', 'knobjokey', 'knobs',
    'knobz', 'knulle', 'kock', 'kondum', 'kondums', 'kraut', 'kuk', 'kuksuger',
    'kum', 'kummer', 'kumming', 'kums', 'kunilingus', 'kunt', 'kunts',
    'kuntz', 'kurac', 'kurwa', 'kusi', 'kyrpa', 'l3i+ch', 'l3itch', 'labia',
    'leatherrestraint', 'leatherstraightjacket', 'lemonparty', 'lesbian',
    'lesbo', 'lezzian', 'lipshits', 'lipshitz', 'lmfao', 'lolita',
    'lovemaking', 'lust', 'lusting', 'm0f0', 'm0fo', 'm45terbate', 'ma5terb8',
    'ma5terbate', 'makemecome', 'malesquirting', 'mamhoon', 'masochist',
    'masokist', 'massterbait', 'masstrbait', 'masstrbate', 'master-bate',
    'masterb8', 'masterbaiter', 'masterbat', 'masterbat*', 'masterbat3',
    'masterbate', 'masterbates', 'masterbation', 'masterbations', 'masturbat',
    'masturbate', 'menageatrois', 'merd', 'mibun', 'milf',
    'missionaryposition', 'mo-fo', 'mof0', 'mofo', 'monkleigh', 'mothafuck',
    'mothafucka', 'mothafuckas', 'mothafuckaz', 'mothafucked', 'mothafucker',
    'mothafuckers', 'mothafuckin', 'mothafucking', 'mothafuckings',
    'mothafucks', 'mothafuker', 'mothafukkah', 'mothafukker', 'mother-fucker',
    'motherfuck', 'motherfucked', 'motherfucker', 'motherfuckers',
    'motherfuckin', 'motherfucking', 'motherfuckings', 'motherfuckka',
    'motherfucks', 'motherfukah', 'motherfuker', 'motherfukkah',
    'motherfukker', 'mouliewop', 'moundofvenus', 'mrhands', 'muff',
    'muffdiver', 'muffdiving', 'muie', 'mulkku', 'muschi', 'mutha',
    'muthafecker', 'muthafucker', 'muthafuckker', 'muthafukah', 'muthafuker',
    'muthafukkah', 'muthafukker', 'muther', 'mutherfucker', 'n1gga', 'n1gger',
    'n1gr', 'nambla', 'nastt', 'nawashi', 'nazi', 'nazis', 'negro', 'neonazi',
    'nepesaurio', 'nigg3r', 'nigg4h', 'nigga', 'niggah', 'niggas', 'niggaz',
    'nigger', 'nigger;', 'niggers', 'nignog', 'nigur;', 'niiger;', 'niigr;',
    'nimphomania', 'nipple', 'nipples', 'nob', 'nobhead', 'nobjocky',
    'nobjokey', 'nsfwimages', 'nude', 'nudity', 'numbnuts', 'nutsack',
    'nympho', 'nymphomania', 'octopussy', 'omorashi', 'onecuptwogirls',
    'oneguyonejar', 'orafis', 'orgasim', 'orgasim;', 'orgasims', 'orgasm',
    'orgasms', 'orgasum', 'orgy', 'oriface', 'orifice', 'orifiss', 'orospu',
    'p0rn', 'packi', 'packie', 'packy', 'paedophile', 'paki', 'pakie', 'paky',
    'panties', 'panty', 'paska', 'pawn', 'pecker', 'pedobear', 'pedophile',
    'peeenus', 'peeenusss', 'peenus', 'pegging', 'peinus', 'pen1s', 'penas',
    'penis', 'penis-breath', 'penisfucker', 'penus', 'penuus', 'perse',
    'phonesex', 'phuc', 'phuck', 'phuk', 'phuked', 'phuker', 'phuking',
    'phukked', 'phukker', 'phukking', 'phuks', 'phuq', 'picka', 'pieceofshit',
    'pierdol', 'pigfucker', 'pillu', 'pimmel', 'pimpis', 'piss', 'pissed',
    'pisser', 'pissers', 'pisses', 'pissflaps', 'pissin', 'pissing', 'pissoff',
    'pisspig', 'pizda', 'playboy', 'pleasurechest', 'polac', 'polack', 'polak',
    'polesmoker', 'ponyplay', 'poof', 'poonani', 'poontsee', 'poop',
    'poopchute', 'porn', 'porno', 'pornography', 'pornos', 'pr0n', 'pr1c',
    'pr1ck', 'pr1k', 'preteen', 'prick', 'pricks', 'princealbertpiercing',
    'pron', 'pthc', 'pube', 'pubes', 'pula', 'pule', 'pusse', 'pussee',
    'pussi', 'pussies', 'pussy', 'pussys', 'puta', 'puto', 'puuke', 'puuker',
    'qahbeh', 'queaf', 'queef', 'queer', 'queers', 'queerz', 'qweers',
    'qweerz', 'qweir', 'raghead', 'ragingboner', 'rape', 'raping', 'rapist',
    'rautenberg', 'recktum', 'rectum', 'retard', 'reversecowgirl', 'rimjaw',
    'rimjob', 'rimming', 'rosypalm', 'rosypalmandher5sisters', 'rustytrombone',
    's&m', 's.o.b.', 's_h_i_t', 'sadism', 'sadist', 'scank', 'scat',
    'schaffer', 'scheiss', 'schlampe', 'schlong', 'schmuck', 'scissoring',
    'screw', 'screwing', 'scroat', 'scrote', 'scrotum', 'semen', 'sex', 'sexo',
    'sexy', 'sh!+', 'sh!t', 'sh1t', 'sh1ter', 'sh1ts', 'sh1tter', 'sh1tz',
    'shag', 'shagger', 'shaggin', 'shagging', 'sharmuta', 'sharmute',
    'shavedbeaver', 'shavedpussy', 'shemale', 'shi+', 'shibari', 'shipal',
    'shit', 'shitdick', 'shite', 'shited', 'shitey', 'shitfuck', 'shitfull',
    'shithead', 'shiting', 'shitings', 'shits', 'shitted', 'shitter',
    'shitters', 'shitting', 'shittings', 'shitty', 'shity', 'shitz', 'shiz',
    'shota', 'shrimping', 'shyt', 'shyte', 'shytty', 'shyty', 'skanck',
    'skank', 'skankee', 'skankey', 'skanks', 'skanky', 'skribz', 'skurwysyn',
    'slanteye', 'slut', 'sluts', 'slutty', 'slutz', 'smegma', 'smut', 'snatch',
    'snowballing', 'sodomize', 'sodomy', 'son-of-a-bitch', 'spac', 'sphencter',
    'spic', 'spierdalaj', 'splooge', 'spooge', 'spreadlegs', 'spunk',
    'strapon', 'strappado', 'stripclub', 'styledoggy', 'suck', 'sucks',
    'suicidegirls', 'suka', 'sultrywomen', 'swastika', 'swinger', 't1tt1e5',
    't1tties', 'taintedlove', 'tastemy', 'teabagging', 'teets', 'teez',
    'testical', 'testicle', 'threesome', 'throating', 'tiedup', 'tightwhite',
    'tit', 'titfuck', 'tits', 'titt', 'tittie5', 'tittiefucker', 'titties',
    'titty', 'tittyfuck', 'tittywank', 'titwank', 'tongueina', 'topless',
    'tosser', 'towelhead', 'tranny', 'tribadism', 'tubgirl', 'turd', 'tushy',
    'tw4t', 'twat', 'twathead', 'twatty', 'twink', 'twinkie', 'twogirlsonecup',
    'twunt', 'twunter', 'undressing', 'upskirt', 'urethraplay', 'urophilia',
    'v14gra', 'v1gra', 'va1jina', 'vag1na', 'vagiina', 'vagina', 'vaj1na',
    'vajina', 'venusmound', 'viagra', 'vibrator', 'violetblue', 'violetwand',
    'vittu', 'vorarephilia', 'voyeur', 'vullva', 'vulva', 'w00se', 'w0p',
    'wang', 'wank', 'wanker', 'wanky', 'wetback', 'wetdream', 'wh00r',
    'wh0re', 'whitepower', 'whoar', 'whore', 'wichser', 'willies', 'willy',
    'womenrapping', 'wop', 'wrappingmen', 'wrinkledstarfish', 'xrated', 'xx',
    'xxx', 'xxxx', 'xxxxx', 'yaoi', 'yed', 'yellowshowers', 'yiffy',
    'zabourah', 'zoophilia'
]
